# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f8dbf31cef22c51eaba67277578b963145473b533f388912c8b47593fb55399d47a1b8dbf8bfbb82cfcf9ff1fc51df3a1e7e916ea78d0cfb42c27032b10caeb2

test:
  secret_key_base: a0909967fda510d17d01e721f268cc84843cc25428bbad260d193fc2afc3cfdf4a44b5f14928c5b8dcfbbabbf95a7c2f7076ac744e5c82fd5346b07e7da72cb0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
